### ISSUE TITLE
Kaomoji

### ISSUE THREAD

**Issue by Madis0** [Sturmlilie/duyguji-client-base#2]
Since vanilla does not include that many Unicode emoji characters, how about incorporating some kaomoji with it?

Popular ones include `¯\_(ツ)_/¯`, `ಠ_ಠ` and `(╯°□°）╯︵ ┻━┻` but there may be more that can be rendered in vanilla.

I didn't make a PR yet because I assume you might want to categorize them differently.

**Comment by Sturmlilie** [comment]
Yes, also currently the UI code reserves a fixed amount of space usually enough for a single character; I'd have to adjust it to be variable. But I definitely want people to be able to add arbitrary emoji-like strings. I'm just not sure whether I should include a default set in duyguji because the list of them is pretty much endless..

**Comment by Madis0** [comment]
> I'm just not sure whether I should include a default set in duyguji because the list of them is pretty much endless.

It is, yes, but not all look good in vanilla.

**Comment by Sturmlilie** [comment]
Maybe a handful ones with an explicit notice that more can be added from many sites on the net would suffice.

**Comment by Sturmlilie** [comment]
With 344affa4b3aca1586bf9ad5018d5035fd020e598 you should be able to use any kaomoji declared in your `vanillla.txt`.

**Comment by Sturmlilie** [comment]
I'm closing this since the number of possible Kaomoji is technically infinite and there is no good predicate for ones that should be included in `vanilla.txt`. It's best to just leave it up to the users to define their own and possibly share them with each other.
