### ISSUE TITLE
Curseforge

### ISSUE THREAD

**Issue by Madis0** [Sturmlilie/duyguji-client-base#6]
Please post this mod to Curseforge so that more people can know about it :)

**Comment by Sturmlilie** [comment]
I will, in time. Originally I wanted to get the full 1.0 feature set done (unicde and custom server emojis) but I might trim that down to just unicode. I don't wanna release it at this point because people might get the impression the feature set will always be limited to what it is now ;)
(closing but feel free to continue commenting if you want)
